packages:
  - .
  - packages/*

allowBuilds:
  '@shopify/react-native-skia': true
  esbuild: false
  msgpackr-extract: false
  react-native-nitro-modules: true
  unrs-resolver: true

nodeLinker: hoisted

overrides:
  'hermes-compiler': '250829098.0.4'
  # TODO: remove after upstream balanced-match CJS compatibility issue is fixed.
  'balanced-match': '1.0.2'
