ignoredBuiltDependencies:
  - esbuild

nodeLinker: hoisted

overrides:
  'hermes-compiler': '250829098.0.4'
  # TODO: remove after upstream balanced-match CJS compatibility issue is fixed.
  'balanced-match': '1.0.2'

onlyBuiltDependencies:
  - '@shopify/react-native-skia'
  - react-native-nitro-modules
  - unrs-resolver
