packages:
  - packages/*

ignoredBuiltDependencies:
  - esbuild

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@shopify/react-native-skia'
  - msgpackr-extract
  - react-native-nitro-modules
  - unrs-resolver

overrides:
  balanced-match: 1.0.2
  hermes-compiler: 250829098.0.4
