/// <reference types="node" />

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const SOURCES = [
  {
    file: 'src/features/chapel/ui/seatmap/ChapelSeatmap1F.tsx',
    floor: '1',
    idPrefix: 'csm-1f',
  },
  {
    file: 'src/features/chapel/ui/seatmap/ChapelSeatmap2F3F.tsx',
    floor: '23',
    idPrefix: 'csm-23f',
  },
] as const;

const NUMBER_OR_COMMAND = /[a-zA-Z]|-?(?:\d*\.)?\d+(?:e[-+]?\d+)?/gi;
const SEAT_PATH = /<G id="(csm-(?:1f|23f))-([A-J]-\d+-\d+)">\s*<Path\s+([\s\S]*?)\/>/g;

const getPathBounds = (path: string) => {
  const tokens = path.match(NUMBER_OR_COMMAND) ?? [];
  let index = 0;
  let command = '';
  let x = 0;
  let y = 0;
  let startX = 0;
  let startY = 0;
  let minX = Number.POSITIVE_INFINITY;
  let minY = Number.POSITIVE_INFINITY;
  let maxX = Number.NEGATIVE_INFINITY;
  let maxY = Number.NEGATIVE_INFINITY;

  const includePoint = () => {
    minX = Math.min(minX, x);
    minY = Math.min(minY, y);
    maxX = Math.max(maxX, x);
    maxY = Math.max(maxY, y);
  };
  const readNumber = () => Number(tokens[index++]);

  while (index < tokens.length) {
    if (/^[a-zA-Z]$/.test(tokens[index])) {
      command = tokens[index++];
    }

    switch (command) {
      case 'H':
      case 'h': {
        x = (command === 'h' ? x : 0) + readNumber();
        includePoint();
        break;
      }
      case 'L':
      case 'l': {
        const relative = command === 'l';
        x = (relative ? x : 0) + readNumber();
        y = (relative ? y : 0) + readNumber();
        includePoint();
        break;
      }
      case 'M':
      case 'm': {
        const relative = command === 'm';
        x = (relative ? x : 0) + readNumber();
        y = (relative ? y : 0) + readNumber();
        startX = x;
        startY = y;
        includePoint();
        command = relative ? 'l' : 'L';
        break;
      }
      case 'V':
      case 'v': {
        y = (command === 'v' ? y : 0) + readNumber();
        includePoint();
        break;
      }
      case 'Z':
      case 'z':
        x = startX;
        y = startY;
        includePoint();
        command = '';
        break;
      default:
        throw new Error(`Unsupported SVG path command: ${command || tokens[index]}`);
    }
  }

  const round = (value: number) => Number(value.toFixed(3));
  return [round(minX), round(minY), round(maxX - minX), round(maxY - minY)] as const;
};

const entries: Array<[string, readonly [number, number, number, number]]> = [];

for (const { file, floor, idPrefix } of SOURCES) {
  const source = readFileSync(resolve(file), 'utf8');

  for (const match of source.matchAll(SEAT_PATH)) {
    if (match[1] !== idPrefix) {
      continue;
    }

    const path = match[3].match(/d="([^"]+)"/)?.[1];
    if (!path) {
      throw new Error(`Missing outline path for ${match[2]}`);
    }
    entries.push([`${floor}:${match[2]}`, getPathBounds(path)]);
  }
}

if (entries.length !== 1163) {
  throw new Error(`Expected 1163 chapel seats, found ${entries.length}`);
}

const rows = entries
  .sort(([left], [right]) => left.localeCompare(right, 'en', { numeric: true }))
  .map(([key, bounds]) => `  '${key}': [${bounds.join(', ')}],`)
  .join('\n');

writeFileSync(
  resolve('src/features/chapel/ui/seatmap/chapel-seat-bounds.ts'),
  `// Generated by scripts/generate-chapel-seat-bounds.ts.\n` +
    `export type ChapelSeatBounds = readonly [x: number, y: number, width: number, height: number];\n\n` +
    `export const chapelSeatBounds: Record<string, ChapelSeatBounds> = {\n${rows}\n};\n`,
);
