name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  build-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Enable corepack
        run: corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Check tests with Vitest
        run: pnpm test

      - name: Check lint with eslint
        run: pnpm lint

      - name: Check format with prettier
        run: pnpm format
